config/routes.rb
Rails.application.routes.draw do
  resources :colleges
  devise_for :users
  resources :users
  resources :bets do
  end
  post "bets/pickem" => "bets#create_pickem"
  resources :money_line_bets, :controller => 'bets'
  resources :spread_bets, :controller => 'bets'
  resources :over_under_bets, :controller => 'bets'
  resources :matches do
    post "open" => "matches#open"
    post "close" => "matches#close"
    post "winner" => "matches#winner"
  end

  resources :wrestlers
  resources :tournaments do
    get "bet" => "tournaments#bet"
    get "display" => "tournaments#display"
    get "not_in_session" => "tournaments#not_in_session"
    get "administer" => "tournaments#administer"
    get "pickem" => "tournaments#pickem"
  end

  root to: "tournaments#index"
end

app/models/user.rb
class User < ApplicationRecord
  include ActionView::Helpers::NumberHelper
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
  has_many :bets, dependent: :destroy
  validates :display_name, length: {minimum: 4, maximum: 25}, allow_blank: false

  INITIAL_BALANCE=100.0

  def admin?
    email == "goggin13@gmail.com"
  end

  def encoded_email
    Base64.encode64(email).chomp
  end

  def formatted_balance
    number_to_currency(balance)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
		@tournament = Tournament.current
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    password = SecureRandom.hex(8)
    @user = User.new(user_params.merge(
      :password => password,
      :password_confirmation => password
    ))

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :avatar, :display_name)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if current_user.admin? %>
    <div class="field">
      <%= form.label :email %>
      <%= form.text_field :email %>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :display_name, "Display Name (max 25 characters)" %>
    <%= form.text_field :display_name %>
  </div>

  <div class="field">
    <%= avatar(user) %>
    <%= form.label :avatar %>
    <%= form.file_field :avatar %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<% content_for :header do %>
  Editing User
<% end %>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<% content_for :header do %>
  Users
<% end %>

<%= link_to("New User", new_user_path) %>

<table>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user_avatar(user) %></td>
        <td><%= user.email %></td>
        <td><%= link_to("Bets", bets_path(user_id: user.id)) %></td>
        <td><%= link_to("Edit", edit_user_path(user)) %></td>
        <td><%= user_tournament_link(user, @tournament) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</ul>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<% content_for :header do %>
  <%= @user.email %>
<% end %>

<p id="notice"><%= notice %></p>

<%= avatar(@user) %>

<p>Email: <%= @user.email %></p>
<p>Display Name: <%= @user.display_name %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>