config/routes.rb
Rails.application.routes.draw do
  resources :colleges
  devise_for :users
  resources :users
  resources :bets do
  end
  post "bets/pickem" => "bets#create_pickem"
  resources :money_line_bets, :controller => 'bets'
  resources :spread_bets, :controller => 'bets'
  resources :over_under_bets, :controller => 'bets'
  resources :matches do
    post "open" => "matches#open"
    post "close" => "matches#close"
    post "winner" => "matches#winner"
  end

  resources :wrestlers
  resources :tournaments do
    get "bet" => "tournaments#bet"
    get "display" => "tournaments#display"
    get "not_in_session" => "tournaments#not_in_session"
    get "administer" => "tournaments#administer"
    get "pickem" => "tournaments#pickem"
  end

  root to: "tournaments#index"
end

app/models/tournament.rb
class Tournament < ApplicationRecord
  has_many :matches, -> { order(weight: :asc) }, dependent: :destroy
  before_save :close_current_match
  after_update :set_tournament_in_sessions

  def current_match
    if current_match_id.present?
      Match.find(current_match_id)
    end
  end

  def complete?
    matches.where("home_score is not null AND away_score is not null").count == matches.count
  end

  def close_current_match
    if current_match_id.present?
      Match.find(current_match_id).update!(closed: true)
    end
  end

  def self.current
    Tournament.where(in_session: true).first!
  end

  def set_tournament_in_sessions
    if self.saved_change_to_in_session? && self.in_session?
      Tournament.where("id != ?", self.id).update(in_session: false)
    end

    true
  end
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  before_action :require_admin!
  before_action :set_tournament, only: [:show, :pickem, :edit, :update, :destroy, :bet, :display, :not_in_session, :administer]
  skip_before_action :authenticate_user!, only: [:bet, :show, :display, :not_in_session]
  skip_before_action :require_admin!, only: [:bet, :show, :display, :not_in_session]

  def bet
    email = Base64.decode64(params[:c])
    user = User.where(email: email).first!
    sign_in(user)
    redirect_to tournament_path(@tournament)
  end

  def display
    @match = @tournament.current_match
    if @match.present?
      @home = @match.home_wrestler
      @home_bets = @match.home_bets
      @away = @match.away_wrestler
      @away_bets = @match.away_bets
    end

    render layout: false
  end

  def not_in_session
  end

  def administer
    @users = User.all
  end

  # GET /tournaments
  # GET /tournaments.json
  def index
    @tournaments = Tournament.all
  end

  # GET /tournaments/1
  # GET /tournaments/1.json
  def show
    @tournament_presenter = TournamentPresenter.new(@tournament)
  end

  def pickem
    @tournament_presenter = TournamentPresenter.new(@tournament, current_user)
  end

  # GET /tournaments/new
  def new
    @tournament = Tournament.new
  end

  # GET /tournaments/1/edit
  def edit
  end

  # POST /tournaments
  # POST /tournaments.json
  def create
    @tournament = Tournament.new(tournament_params)

    respond_to do |format|
      if @tournament.save
        format.html { redirect_to @tournament, notice: 'Tournament was successfully created.' }
        format.json { render :show, status: :created, location: @tournament }
      else
        format.html { render :new }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tournaments/1
  # PATCH/PUT /tournaments/1.json
  def update
    respond_to do |format|
      if @tournament.update(tournament_params)
        format.html { redirect_to tournament_administer_path(@tournament), notice: 'Tournament was successfully updated.' }
        format.json { render :show, status: :ok, location: @tournament }
      else
        format.html { render :edit }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tournaments/1
  # DELETE /tournaments/1.json
  def destroy
    @tournament.destroy
    respond_to do |format|
      format.html { redirect_to tournaments_url, notice: 'Tournament was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tournament
      @tournament = Tournament.find(params[:id] || params[:tournament_id])
    end

    # Only allow a list of trusted parameters through.
    def tournament_params
      params.require(:tournament).permit(:name, :current_match_id, :in_session, :show_take_home_data)
    end
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/tournaments/_bet_form.html.erb
<% existing_bet = Bet.where(user: current_user, match: bet.match, type: bet.type, wager: bet.wager).first %>

<% if bet.match.closed? %>

  <% if existing_bet.present? %>
    <% if bet.match.complete? %>
      <% if existing_bet.payout > 0 %>
        <div class="bet_payout won">
          +<%= number_to_currency(existing_bet.net_payout) %>
        </div>
      <% else %>
        <div class="bet_payout lost">
          -<%= number_to_currency(existing_bet.amount) %>
        </div>
      <% end %>
    <% else %>
      <div class="locked_bet_text">
        <%= existing_bet.label %>
        <br/>
        <span class="payout_ratio">(<%= existing_bet.formatted_payout_ratio %>)</span>
      </div>
    <% end %>
  <% else %>
    <%= image_tag("lock.png", class:"lock_image") %>
  <% end %>

<% elsif existing_bet.present? %>

  <%= link_to existing_bet.remove_message, existing_bet, method: :delete %>

<% else %>

  <% if bet.is_a?(SpreadBet) %>
    <%= bet.my_spread %>
  <% end %>

  <% if bet.is_a?(OverUnderBet) %>
    <%= bet.submit_label %>
  <% end %>

  <p class="payout_ratio">
    <%= bet.formatted_payout_ratio %>
  </p>

  <div class="hidden_bet_form hidden">

    <p class="bet_title">
      <%= bet.title %>
      <span class="payout_ratio">
        <br/>(<%= bet.formatted_payout_ratio %>)
      </span>
    </p>

    <%= form_with(model: bet.becomes(Bet), local: true) do |form| %>
      <%= form.hidden_field :match_id %>
      <%= form.hidden_field :type %>
      <%= form.hidden_field :wager %>

      <div class="wager_field">
        <span class="payout_ratio hidden">
          <%= bet.payout_ratio %>
        </span>
        <p>
          Available: <span class="user_balance">$<%= current_user.balance %></span>
        </p>
        <p>
          Wager: $<%= form.number_field :amount, step: "any" %>
        </p>
        <p>
          To Win: $<span class="to_win_amount"><%= Bet.calculate_payout(5.0, bet.payout_ratio) %></span>
        </p>
      </div>


      <div class="actions hidden">
        <%= form.submit value: bet.submit_label %>
      </div>
    <% end %>

    <div class='bet_explanation'>
      You win if <%= bet.win_scenario %>
      <% if bet.respond_to?(:moneyback_scenario) %>
        <br/>Money back if <%= bet.moneyback_scenario %>
      <% end %>
    </div>
  </div>

<% end %>

app/views/tournaments/_form.html.erb
<%= form_with(model: tournament, local: true) do |form| %>
  <% if tournament.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tournament.errors.count, "error") %> prohibited this tournament from being saved:</h2>

      <ul>
        <% tournament.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :in_session %>
    <%= form.check_box(:in_session) %>
  </div>

  <div class="field">
    <%= form.label :show_take_home_data %>
    <%= form.check_box(:show_take_home_data) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tournaments/_pickem_bet_form.html.erb
<% existing_bet = Bet.where(user: current_user, match: bet.match, type: bet.type, wager: bet.wager).first %>

<div class="pickem_form_panel <%= existing_bet.present? ? 'selected' : 'not_selected' %>">
  <% if bet.match.closed? %>
    <%= bet.pick_em_label %>
  <% else %>
    <%= form_with(model: bet.becomes(Bet), local: true, url: bets_pickem_path) do |form| %>
      <%= form.hidden_field :match_id %>
      <%= form.hidden_field :type %>
      <%= form.hidden_field :wager %>
      <%= form.hidden_field :amount %>

      <%= form.submit value: bet.pick_em_label %>
    <% end %>

    <div class="pickem_form_wrestler <%= bet.wager %>">
      <% if bet.wager == "away" %>
        <%= college_logo(bet.match.away_wrestler.college, size: "50x50") %>
      <% else %>
        <%= college_logo(bet.match.home_wrestler.college, size: "50x50") %>
      <% end %>
    </div>
  <% end %>

</div>

app/views/tournaments/_tournament_current_match.html.erb
<%= form_with(url: tournament_path(tournament), method: "put") do %>

  <%= select_tag "tournament[current_match_id]", options_from_collection_for_select(
    tournament.matches.order("weight ASC"),
    "id",
    "title",
    tournament.current_match_id,
  ), 
  include_blank: true,
  onchange: "this.form.submit();" %>

  <%= submit_tag("Set current match") %>
<% end %>

app/views/tournaments/_wrestler.html.erb
<%= avatar(wrestler, size: "150x200") %>
<p>
  <% if wrestler.college_year %>
    <%= college_logo(wrestler.college, class: "college_logo") %> '<%= (wrestler.college_year - 2000).to_s.rjust(2, "0") %>
  <% end %>
  <br/>
  <%= wrestler.bio.gsub("\n", "<br/>").html_safe %>
</p>

app/views/tournaments/administer.html.erb
<% content_for :header do %>
  <%= @tournament.name %>
<% end %>

<%= render partial: "tournament_current_match", locals: {tournament: @tournament} %>

<table>
  <thead>
    <tr>
      <th></th>
      <th>Weight</th>
      <th>Closed?</th>
      <th>Away wrestler</th>
      <th>Home wrestler</th>
      <th>Over/Under</th>
      <th>Score</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @tournament.matches.each do |match| %>
      <tr>
        <td>
          <% if match.id == @tournament.current_match_id %>
            Live
          <% end %>
        </td>
        <td><%= match.weight %></td>
        <td><%= match.closed? %></td>
        <td><%= match.away_wrestler.name %> (<%= away_spread(match) %>)</td>
        <td><%= match.home_wrestler.name %> (<%= home_spread(match) %>)</td>
        <td><%= match.over_under %></td>
        <td><%= match.away_score %>-<%= match.home_score %></td>
        <td><%= link_to 'Edit', edit_match_path(match) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Match', new_match_path %>

app/views/tournaments/display.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wrestling</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'display', 'data-turbolinks-track': 'reload' %>
  </head>

  <body
    class="display"
    data-tournament-id="<%= @tournament.id %>"
    data-match-id="<%= @match.present? ? @match.id : -1 %>">


    <% if @match.present? %>
      <div id="wrestler_away">

        <%= avatar(@match.away_wrestler, size: "500x500", class: "wrestler_avatar") %><br/>

        <div class="fatality"><%= random_fatality %></div>

        <p class="wrestler_name">
          <%= @match.away_wrestler.name %>
        </p>

        <p class="wrestler_college_logo">
          <%= college_logo(@match.away_wrestler.college, size: "50x50") %>
        </p>

        <ul class="user_bets"`>
          <% @away_bets.each do |bet| %>
            <li>
              <%= user_avatar(bet.user, "100x100") %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <% if @match.present? %>
      <div id="wrestler_home">
        <%= avatar(@match.home_wrestler, size: "500x500", class: "wrestler_avatar") %><br/>
        <div class="fatality"><%= random_fatality %></div>
        <p class="wrestler_name">
          <%= @match.home_wrestler.name %>
        </p>
        <p class="wrestler_college_logo">
          <%= college_logo(@match.home_wrestler.college, size: "50x50") %>
        </p>
        <ul class="user_bets"`>
          <% @home_bets.each do |bet| %>
            <li>
              <%= user_avatar(bet.user, "100x100") %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <table id="leaderboard">
      <% previous_rank = -1 %>
      <% Leaderboard.new(@tournament).pickem_results.each do |user_data| %>
        <tr>
          <td>
            <div class="leaderboard_data">
              <% if user_data[:rank] != previous_rank %>
                <%= user_data[:rank].ordinalize %>
                <% previous_rank = user_data[:rank] %>
              <% end %>
            </div>
          </td>
          <td><div class="leaderboard_data"><%= user_avatar(user_data[:user], "50x50") %></div></td>
          <td><div class="leaderboard_data"><%= user_data[:user].display_name %></div></td>
          <td><div class="leaderboard_data"><%= user_data[:correct_picks] %></div></td>
        </tr>
      <% end %>
    </table>
  </body>
</html>

app/views/tournaments/edit.html.erb
<% content_for :header do %>
  Editing Tournament
<% end %>

<%= render 'form', tournament: @tournament %>

<%= link_to 'Show', @tournament %> |
<%= link_to 'Back', tournaments_path %>

app/views/tournaments/index.html.erb
<% content_for :header do %>
  Tournaments
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Live?</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tournaments.each do |tournament| %>
      <tr>
        <td><%= tournament.name %></td>
        <td><%= tournament.in_session %></td>
        <td><%= link_to 'Show', tournament_path(tournament) %></td>
        <td><%= link_to 'Show PickEm', tournament_pickem_path(tournament) %></td>
        <td><%= link_to 'Administer', tournament_administer_path(tournament) %></td>
        <td><%= link_to 'Display', tournament_display_path(tournament) %></td>
        <td><%= link_to 'Edit', edit_tournament_path(tournament) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tournament', new_tournament_path %>

app/views/tournaments/new.html.erb
<% content_for :header do %>
  New Tournament
<% end %>

<%= render 'form', tournament: @tournament %>

<%= link_to 'Back', tournaments_path %>

app/views/tournaments/not_in_session.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wrestling</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="display" data-tournament-id="<%= @tournament.id %>">

    <div id="leaderboard">
      <% Leaderboard.new(@tournament).results.each do |rank, users| %>
        <div class="position">
          <span "position label"><%= rank.ordinalize %> : <%= number_to_currency(users.first[1] / 100.0) %> </span>
          <div class="users">
            <% users.each do |user, payout| %>
              <%= user_avatar(user, "50x50") %> 
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <div id="leaderboard-buffer"></div>


  </body>
</html>

app/views/tournaments/pickem.html.erb
<% content_for :header do %>
  <%= current_user.email %>'s Betslip
<% end %>

<% content_for :notices do %>
  <br/>
<% end %>

<div id="user_id" class="hidden"><%= current_user.id %></div>

<div id="pickem_list">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <h2>
    Click on a wrestler to place a bet
  </h2>

  <ul class="tournament-match-ups">
    <li>
      You have made <%= @tournament_presenter.pickem_count %> correct picks so far
    </li>


    <% @tournament_presenter.matches.order("weight ASC").each do |match| %>

      <li>
        <% if match.complete? %>
            <% if @tournament_presenter.pickem_win?(match) %>
              <p class="pickem_won">
            <% else %>
              <p class="pickem_lost">
            <% end %>
              <%= match.weight %>:
              <%= match.winner.name %> wins
              <%= [match.home_score, match.away_score].max %>-<%= [match.home_score, match.away_score].min %>
            </p>
        <% else %>
          <p>
            <hr/>

            <% if match.closed? %>
              <%= image_tag("lock.png", class:"lock_image") %>
            <% end %>

            <%= match.weight %> lbs

            <% if match.closed? %>
              <%= image_tag("lock.png", class:"lock_image") %>
            <% end %>

            <% bet = PickemBet.new(amount: 1.0, match: match, wager: "away") %>
            <%= render partial: "pickem_bet_form", locals: {bet: bet} %>

            <% bet = PickemBet.new(amount: 1.0, match: match, wager: "home") %>
            <%= render partial: "pickem_bet_form", locals: {bet: bet} %>
          </p>
        <% end %>
      </li>

    <% end %>
  </ul>

  <% if current_user.admin? %>
    <hr/>
    <%= link_to 'Edit', edit_tournament_path(@tournament) %> |
    <%= link_to 'Back', tournaments_path %>
  <% end %>
</div>

app/views/tournaments/show.html.erb
<% content_for :header do %>
  <%= current_user.email %>'s Betslip
<% end %>

<% content_for :notices do %>
  <br/>
<% end %>

<div id="user_id" class="hidden"><%= current_user.id %></div>

<div id="center-match-ups">
  <p>
    Available Funds:
    <span id="user_balance" class="user_balance"><%= number_to_currency(current_user.balance, precision: 2) %></span>
  </p>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <p id="instructions">
    Click on any box to start betting
  </p>

  <ul class="tournament-match-ups">

    <div id="bet_pop_up">
      <div id="bet_pop_up_content">
      </div>

      <div id="bet_pop_up_buttons">
        <button id="submit_pop_up_form">Wager!</button>
        <br/>
        <button id="close_bet_pop_up">Never mind</button>
      </div>
    </div>

    <% @tournament_presenter.matches.order("weight ASC").each do |match| %>
      <li class="tournament-match-up <%= match.open? ? "open" : "closed" %>" data-match-id="<%= match.id %>">
        <hr/>

        <% if match.complete? %>
          <p>
            <%= match.winner.name %> wins
            <%= [match.home_score, match.away_score].max %>-<%= [match.home_score, match.away_score].min %>
          </p>
        <% end %>

        <table>
          <tr class="first_row">
            <th><%= match.weight %> lbs</th>
            <th>Spread</th>
            <th>Moneyline</th>
            <th>Total</th>
          </tr>

          <tr>
            <th><%= match.away_wrestler.name %></th>
            <% @tournament_presenter.bets_for_match(match, 0).each do |bet| %>
              <td class="<%= bet.class.name.underscore %>_<%= bet.wager %>">
                <%= render partial: "bet_form", locals: {bet: bet} %>
              </td>
            <% end %>
          </tr>
          <tr>
            <th><%= match.home_wrestler.name %></th>
            <% @tournament_presenter.bets_for_match(match, 1).each do |bet| %>
              <td class="<%= bet.class.name.underscore %>_<%= bet.wager %>">
                <%= render partial: "bet_form", locals: {bet: bet} %>
              </td>
            <% end %>
          </tr>
        </table>

      </li>

    <% end %>
  </ul>

  <% if current_user.admin? %>
    <hr/>
    <%= link_to 'Edit', edit_tournament_path(@tournament) %> |
    <%= link_to 'Back', tournaments_path %>
  <% end %>
</div>