config/routes.rb
Rails.application.routes.draw do
  resources :colleges
  devise_for :users
  resources :users
  resources :bets do
  end
  post "bets/pickem" => "bets#create_pickem"
  resources :money_line_bets, :controller => 'bets'
  resources :spread_bets, :controller => 'bets'
  resources :over_under_bets, :controller => 'bets'
  resources :matches do
    post "open" => "matches#open"
    post "close" => "matches#close"
    post "winner" => "matches#winner"
  end

  resources :wrestlers
  resources :tournaments do
    get "bet" => "tournaments#bet"
    get "display" => "tournaments#display"
    get "not_in_session" => "tournaments#not_in_session"
    get "administer" => "tournaments#administer"
    get "pickem" => "tournaments#pickem"
  end

  root to: "tournaments#index"
end

app/models/college.rb
class College < ApplicationRecord
  has_one_attached :logo
  validates_presence_of :name
end

app/controllers/colleges_controller.rb
class CollegesController < ApplicationController
  before_action :set_college, only: [:show, :edit, :update, :destroy]

  # GET /colleges
  # GET /colleges.json
  def index
    @colleges = College.all
  end

  # GET /colleges/1
  # GET /colleges/1.json
  def show
  end

  # GET /colleges/new
  def new
    @college = College.new
  end

  # GET /colleges/1/edit
  def edit
  end

  # POST /colleges
  # POST /colleges.json
  def create
    @college = College.new(college_params)

    respond_to do |format|
      if @college.save
        format.html { redirect_to @college, notice: 'College was successfully created.' }
        format.json { render :show, status: :created, location: @college }
      else
        format.html { render :new }
        format.json { render json: @college.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colleges/1
  # PATCH/PUT /colleges/1.json
  def update
    respond_to do |format|
      if @college.update(college_params)
        format.html { redirect_to @college, notice: 'College was successfully updated.' }
        format.json { render :show, status: :ok, location: @college }
      else
        format.html { render :edit }
        format.json { render json: @college.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colleges/1
  # DELETE /colleges/1.json
  def destroy
    @college.destroy
    respond_to do |format|
      format.html { redirect_to colleges_url, notice: 'College was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_college
      @college = College.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def college_params
      params.require(:college).permit(:name, :logo)
    end
end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/views/colleges/_form.html.erb
<%= form_with(model: college, local: true, multipart: true) do |form| %>
  <% if college.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(college.errors.count, "error") %> prohibited this college from being saved:</h2>

      <ul>
        <% college.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :logo %>
    <%= form.file_field :logo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/colleges/edit.html.erb
<% content_for :header do %>
  Editing College
<% end %>

<%= render 'form', college: @college %>

<%= link_to 'Show', @college %> |
<%= link_to 'Back', colleges_path %>

app/views/colleges/index.html.erb
<% content_for :header do %>
  Colleges
<% end %>

<%= link_to 'New College', new_college_path %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @colleges.each do |college| %>
      <tr>
        <td><%= college.name %></td>
        <td><%= college_logo(college) %></td>
        <td><%= link_to 'Show', college %></td>
        <td><%= link_to 'Edit', edit_college_path(college) %></td>
        <td><%= link_to 'Destroy', college, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New College', new_college_path %>

app/views/colleges/new.html.erb
<% content_for :header do %>
  New College
<% end %>

<%= render 'form', college: @college %>

<%= link_to 'Back', colleges_path %>

app/views/colleges/show.html.erb
<% content_for :header do %>
  <%= @college.name %>
<% end %>

<p id="notice"><%= notice %></p>

<p>
  <%= college_logo(@college) %>
</p>

<%= link_to 'Edit', edit_college_path(@college) %> |
<%= link_to 'Back', colleges_path %>
<%= link_to 'New College', new_college_path %>