config/routes.rb
Rails.application.routes.draw do
  resources :colleges
  devise_for :users
  resources :users
  resources :bets do
  end
  post "bets/pickem" => "bets#create_pickem"
  resources :money_line_bets, :controller => 'bets'
  resources :spread_bets, :controller => 'bets'
  resources :over_under_bets, :controller => 'bets'
  resources :matches do
    post "open" => "matches#open"
    post "close" => "matches#close"
    post "winner" => "matches#winner"
  end

  resources :wrestlers
  resources :tournaments do
    get "bet" => "tournaments#bet"
    get "display" => "tournaments#display"
    get "not_in_session" => "tournaments#not_in_session"
    get "administer" => "tournaments#administer"
    get "pickem" => "tournaments#pickem"
  end

  root to: "tournaments#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wrestling</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user.present? && current_user.admin? %>
      <%= link_to("Tournaments", tournaments_path) %>
      <%= link_to("Wrestlers", wrestlers_path) %>
      <%= link_to("Colleges", colleges_path) %>
      <%= link_to("Users", users_path) %>
      <%= link_to("Bets", bets_path) %>
      <%= link_to('Logout', destroy_user_session_path, method: :delete) %> 
    <% end %>

    <h1><%= yield(:header) %></h1>

    <% if content_for?(:notices) %>
      <%= yield(:notices) %>
    <% else %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <% end %>

    <%= yield %>

    <div id="footer">
      <hr/>
      <% if current_user.present? && current_user.admin? %>
        <p>
          <%= link_to "Betslip", tournament_path(Tournament.current) %>
        </p>
        <p>
          <%= link_to "Edit my Profile", edit_user_path(current_user) %>
        </p>
      <% end %>
    </div>
  </body>
</html>